version: "3.8"
services:
  drupal:
    container_name: portable_news_app
    image: drupal:9.4.5-apache-buster
    ports:
       - 8080:80
    volumes:
       - ./drupal:/opt/drupal
    depends_on:
       - database
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
  
  database:
    container_name: portable_news_db
    image: mariadb:10
    ports:
      - 8086:3306
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
       - ./data:/docker-entrypoint-initdb.d
       - db-data:/var/lib/mysql
volumes:
     db-data: